name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Thay đổi branch nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Thay đổi phiên bản Node.js nếu cần

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run deploy  # Thay đổi lệnh build nếu cần

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Sử dụng token từ GitHub Secrets
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # Thêm account ID nếu cần
          projectName: neon-portfolio  # Thay bằng tên dự án của bạn
          directory: ./dist  # Thay đổi thư mục build nếu cần
